script_path = os.path.dirname(os.path.abspath(sys.argv[0])) 
include_path = os.path.join(script_path, os.pardir, os.pardir, "!include", "util.sikuli")
sys.path.append(include_path)
import util
reload(util)
addImagePath(include_path)

setAutoWaitTimeout(30)
util.pre_test()

# Read credentials from the secrets file.
credentials = util.get_credentials(os.path.join(include_path, os.pardir, "secrets.txt"))
domain = credentials.get("Domain")
api_key = credentials.get("APIKey")

# Read extra parameters from the extra.txt.
with open(os.path.join(script_path, os.pardir, "extra.txt"), "r") as file:
    extra = file.read().replace("\n", "")

# Setup.
click("runas_password.png")
wait(2)
paste("password")
wait(2)
type(Key.ENTER)
wait("runas_ready.png")
wait(2)
paste("turbo config --domain=" + domain)
wait(2)
type(Key.ENTER)
if api_key:
    wait(2)
    paste("turbo login --api-key=" + api_key)
    wait(2)
    type(Key.ENTER)
wait(5)
paste("turbo pull xvm")
wait(2)
type(Key.ENTER)
wait(10)
paste('turbo try postgresql/postgresql:16 --startup-file=cmd --working-dir=C:\pgsql --mount C:\pg-data --name="test" ' + extra)
wait(2)
type(Key.ENTER)
wait(10)
setAutoWaitTimeout(60)
wait("pgsql_ready.png")
click("pgsql_ready.png")
wait(2)
paste("run-postgre-sql.bat")
wait(2)
type(Key.ENTER)
wait("pgsql_db_ready.png")
type("c", Key.CTRL)
wait("pgsql_terminate_batch.png")
type("y")
type(Key.ENTER)
wait(2)
paste("cd C:\pgsql")
wait(2)
type(Key.ENTER)
wait(2)
paste("pg_ctl start")
wait(2)
type(Key.ENTER)
wait("pgsql_started.png")
type("psql")
type(Key.ENTER)
wait("pgsql_password.png")
type("postgres")
type(Key.ENTER)
wait("pgsql_console.png")
wait(2)

# pgsql commands and pgvector.
paste("CREATE TABLE Employee (EmployeeID INT PRIMARY KEY, FirstName VARCHAR(50), LastName VARCHAR(50), Age INT);")
wait(2)
type(Key.ENTER)
wait("pgsql_result_1.png")
wait(2)
paste("INSERT INTO Employee (EmployeeID, FirstName, LastName, Age) VALUES (1, 'John', 'Doe', 30), (2, 'Jane', 'Smith', 25), (3, 'David', 'Johnson', 35);")
wait(2)
type(Key.ENTER)
wait("pgsql_result_2.png")
wait(2)
paste("SELECT * FROM Employee;")
wait(2)
type(Key.ENTER)
wait("pgsql_result_3.png")
wait(2)

# Check if the session terminates.
type("\q")
wait(2)
type("c", Key.CTRL)
wait(2)
type("exit")
wait(2)
type(Key.ENTER)
run("turbo stop test")
wait(20)
assert("test" not in run("turbo sessions"))
